### ISSUE TITLE
Template build bug

### ISSUE THREAD

**Issue by Esword618** [PylotLight/wails-hmtx-templ#3] opened 2023-11-02 09:16 UTC
I reported an error using the wails dev command.
<img width="381" alt="image" src="https://github.com/PylotLight/wails-htmx-templ-template/assets/73058062/2aecad1f-abe8-4955-be93-6259ad686a06">
I find it is the place mentioned in the picture below.
<img width="684" alt="image" src="https://github.com/PylotLight/wails-htmx-templ-template/assets/73058062/8adb7cd3-3a3c-4622-86d9-152042549924">

**Comment by PylotLight** [comment] 2023-11-02 13:30
Hey, 

Have you changed the components module import from changeme? 

Double check at the top where the components import is coming from for me. 

this section in app.go needs to match what's in the go.mod as we have to import the components module/folder.
```
import (
	"changeme/components"
...
)
```

**Comment by PylotLight** [comment] 2023-11-09 13:47
Let me know if you have any further issues, otherwise will close this for now.

**Closed as completed** 2023-11-09 13:48 UTC
Labels: question

**Comment by angelside** [comment] 2023-12-09 00:44
This was still an issue but I figured it out.

The reason is that **TestPage()** and **ModalPreview()** are not in the compiled **components/templates_templ.go** file. _(But they are in templates.templ)_

---
Implementation is missing for that "modal" thing:

In app.go add the modal page below /greet page
```go
{"/greet", "Greet form"},
{"/modal", "Modal test"},
```

Build the template again:

You need templ binary in your path.
```shell
go install github.com/a-h/templ/cmd/templ@latest
```

Re-build the template
```shell
~ cd components
~ rm -rf templates_templ.go
~ templ generate
~ cd ..
~ wails dev
```

---

The real thing is; that now we need some way to watch and build templates on change.


![image](https://github.com/PylotLight/wails-htmx-templ-template/assets/7515/ceb2a4b5-0962-4afe-b5d2-a1a2d3d2dc68)

**Comment by PylotLight** [comment] 2023-12-09 02:36
@angelside  FYI this looks like a different issue than the first user as far as I can tell but glad you figured it out.

> The real thing is; that now we need some way to watch and build templates on change.
`templ generate --watch will watch the current directory and will templ files if changes are detected.`
https://templ.guide/commands-and-tools/hot-reload/#built-in

**Comment by angelside** [comment] 2023-12-09 03:08
It was the same issue, that's why I found this issue. We will have the same error if we use it as-is.

Actually, it is easy to reproduce:

```
~ wails init -n "wails-htmx-templ-template" -t https://github.com/PylotLight/wails-htmx-templ-template
~ cd wails-htmx-templ-template
~ wails dev
```

Because your compiled templates do not have that function go fires the errors.


![image](https://github.com/PylotLight/wails-htmx-templ-template/assets/7515/2779c8b9-048a-4a1a-8ddf-16cf9aaf4ece)

**Comment by PylotLight** [comment] 2023-12-09 05:35
@angelside Apologies you were correct, I wasn't reading the messages properly or something :P
Updated those files now, cheers!
